// src/components/admin/InterRaterReliability.svelte
<script lang="ts">
  import type { AnalyticsData } from '../../lib/analytics';

  interface Props {
    data: AnalyticsData;
  }

  let { data }: Props = $props();

  const questionLabels: Record<string, string> = {
    '1': 'Q1: Notación',
    '2': 'Q2: Tonalidad',
    '3': 'Q3: Instrumento',
  };

  const typeLabels: Record<string, string> = {
    binary: 'Binaria',
    ranking: 'Ranking',
  };

  function alphaColor(alpha: number): string {
    if (alpha >= 0.8) return 'text-emerald-600';
    if (alpha >= 0.667) return 'text-accent-600';
    if (alpha >= 0.4) return 'text-amber-600';
    return 'text-red-500';
  }

  function alphaBg(alpha: number): string {
    if (alpha >= 0.8) return 'bg-emerald-100';
    if (alpha >= 0.667) return 'bg-accent-100';
    if (alpha >= 0.4) return 'bg-amber-100';
    return 'bg-red-100';
  }

  function agreementColor(agreement: number): string {
    if (agreement >= 0.8) return 'bg-emerald-500';
    if (agreement >= 0.6) return 'bg-emerald-400';
    if (agreement >= 0.4) return 'bg-amber-400';
    if (agreement >= 0.2) return 'bg-amber-500';
    return 'bg-red-400';
  }

  function agreementOpacity(agreement: number): string {
    return `opacity: ${0.3 + agreement * 0.7}`;
  }

  // Build evaluator pair matrix
  const evaluatorNames = $derived(
    [...new Set(data.interRater.pairwiseAgreement.flatMap(p => [p.evaluator1, p.evaluator2]))]
      .map(id => {
        const ev = data.evaluators.find(e => e.id === id);
        return { id, name: ev?.name || id.slice(0, 8) };
      })
  );

  const insufficientData = $derived(data.evaluators.length < 2);
</script>

<div class="space-y-4">
  <!-- Alpha overview -->
  <div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
    <div class="px-5 py-4 border-b border-surface-700/50">
      <h3 class="font-serif text-base font-semibold text-surface-100">Fiabilidad Inter-Evaluador</h3>
      <p class="text-xs text-surface-500 mt-1">Alpha de Krippendorff — concordancia entre evaluadores</p>
    </div>

    {#if insufficientData}
      <div class="px-5 py-12 text-center text-surface-500 font-serif italic">
        Se necesitan al menos 2 evaluadores para calcular la fiabilidad inter-evaluador
      </div>
    {:else}
      <div class="p-5">
        <!-- Global alpha -->
        <div class="flex items-center gap-4 mb-6">
          <div class="flex-1">
            <span class="text-xs text-surface-500 uppercase tracking-widest">Alpha global</span>
            <div class="flex items-baseline gap-2 mt-1">
              <span class="font-serif text-4xl font-semibold tabular-nums {alphaColor(data.interRater.krippendorffAlpha)}">
                {data.interRater.krippendorffAlpha.toFixed(3)}
              </span>
              <span class="text-sm {alphaBg(data.interRater.krippendorffAlpha)} {alphaColor(data.interRater.krippendorffAlpha)} px-2 py-0.5 rounded font-medium">
                {#if data.interRater.krippendorffAlpha >= 0.8}Excelente
                {:else if data.interRater.krippendorffAlpha >= 0.667}Aceptable
                {:else if data.interRater.krippendorffAlpha >= 0.4}Moderada
                {:else}Baja{/if}
              </span>
            </div>
          </div>

          <!-- Scale reference -->
          <div class="text-xs text-surface-500 space-y-1 border-l border-surface-700 pl-4">
            <div class="flex items-center gap-2"><span class="w-2 h-2 rounded-full bg-emerald-500"></span> ≥ 0.80 Excelente</div>
            <div class="flex items-center gap-2"><span class="w-2 h-2 rounded-full bg-accent-500"></span> ≥ 0.67 Aceptable</div>
            <div class="flex items-center gap-2"><span class="w-2 h-2 rounded-full bg-amber-500"></span> ≥ 0.40 Moderada</div>
            <div class="flex items-center gap-2"><span class="w-2 h-2 rounded-full bg-red-400"></span> &lt; 0.40 Baja</div>
          </div>
        </div>

        <!-- Per-question and per-type alpha -->
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <!-- Per question -->
          <div>
            <span class="text-xs text-surface-500 uppercase tracking-widest block mb-2">Por pregunta</span>
            <div class="space-y-2">
              {#each Object.entries(data.interRater.alphaPerQuestion) as [qId, alpha]}
                <div class="flex items-center justify-between bg-surface-850 rounded px-3 py-2">
                  <span class="text-sm text-surface-300">{questionLabels[qId] || `Q${qId}`}</span>
                  <span class="text-sm font-mono font-semibold tabular-nums {alphaColor(alpha)}">{alpha.toFixed(3)}</span>
                </div>
              {/each}
            </div>
          </div>

          <!-- Per type -->
          <div>
            <span class="text-xs text-surface-500 uppercase tracking-widest block mb-2">Por tipo de pregunta</span>
            <div class="space-y-2">
              {#each Object.entries(data.interRater.alphaPerQuestionType) as [type, alpha]}
                <div class="flex items-center justify-between bg-surface-850 rounded px-3 py-2">
                  <span class="text-sm text-surface-300">{typeLabels[type] || type}</span>
                  <span class="text-sm font-mono font-semibold tabular-nums {alphaColor(alpha)}">{alpha.toFixed(3)}</span>
                </div>
              {/each}
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>

  <!-- Pairwise agreement heatmap -->
  {#if !insufficientData && evaluatorNames.length > 1}
    <div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
      <div class="px-5 py-4 border-b border-surface-700/50">
        <h3 class="font-serif text-base font-semibold text-surface-100">Concordancia por Pares</h3>
        <p class="text-xs text-surface-500 mt-1">Porcentaje de acuerdo exacto entre evaluadores</p>
      </div>

      <div class="p-5 overflow-x-auto">
        <table class="mx-auto">
          <thead>
            <tr>
              <th class="px-2 py-1"></th>
              {#each evaluatorNames as ev}
                <th class="px-2 py-1 text-xs text-surface-500 font-medium text-center truncate max-w-[80px]">{ev.name}</th>
              {/each}
            </tr>
          </thead>
          <tbody>
            {#each evaluatorNames as row}
              <tr>
                <td class="px-2 py-1 text-xs text-surface-500 font-medium truncate max-w-[80px]">{row.name}</td>
                {#each evaluatorNames as col}
                  {#if row.id === col.id}
                    <td class="px-1 py-1">
                      <div class="w-12 h-10 bg-surface-800 rounded flex items-center justify-center text-xs text-surface-600">—</div>
                    </td>
                  {:else}
                    {@const pair = data.interRater.pairwiseAgreement.find(
                      p => (p.evaluator1 === row.id && p.evaluator2 === col.id) ||
                           (p.evaluator1 === col.id && p.evaluator2 === row.id)
                    )}
                    {@const agreement = pair?.agreement ?? 0}
                    <td class="px-1 py-1">
                      <div class="w-12 h-10 rounded flex items-center justify-center text-xs font-mono font-semibold text-white {agreementColor(agreement)}"
                           style={agreementOpacity(agreement)}>
                        {(agreement * 100).toFixed(0)}%
                      </div>
                    </td>
                  {/if}
                {/each}
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
    </div>
  {/if}

  <!-- Evaluator bias detection -->
  {#if data.evaluators.length > 0}
    <div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
      <div class="px-5 py-4 border-b border-surface-700/50">
        <h3 class="font-serif text-base font-semibold text-surface-100">Detección de Sesgo</h3>
        <p class="text-xs text-surface-500 mt-1">Desviación de cada evaluador respecto a la media global</p>
      </div>

      <div class="p-5 space-y-3">
        {#each data.evaluators as evaluator}
          {@const bias = evaluator.bias}
          {@const absBias = Math.abs(bias)}
          {@const biasColor = absBias < 0.3 ? 'text-emerald-600' : absBias < 0.7 ? 'text-amber-600' : 'text-red-500'}
          {@const barColor = bias >= 0 ? 'bg-accent-500' : 'bg-amber-500'}
          <div class="flex items-center gap-3">
            <span class="text-sm text-surface-300 w-28 truncate shrink-0">{evaluator.name}</span>
            <div class="flex-1 flex items-center gap-2">
              <!-- Centered bar -->
              <div class="flex-1 h-3 bg-surface-800 rounded-full relative overflow-hidden">
                {#if bias >= 0}
                  <div class="absolute left-1/2 h-full {barColor} rounded-r-full"
                       style="width: {Math.min(absBias / 2 * 100, 50)}%"></div>
                {:else}
                  <div class="absolute right-1/2 h-full {barColor} rounded-l-full"
                       style="width: {Math.min(absBias / 2 * 100, 50)}%"></div>
                {/if}
                <div class="absolute left-1/2 top-0 bottom-0 w-px bg-surface-600"></div>
              </div>
              <span class="text-xs font-mono tabular-nums w-14 text-right {biasColor}">
                {bias >= 0 ? '+' : ''}{bias.toFixed(2)}
              </span>
            </div>
          </div>
        {/each}
      </div>
    </div>
  {/if}
</div>

// src/components/react/admin/InterRaterReliability.tsx
import { useMemo } from "react";
import type { AnalyticsData } from "../../../lib/analytics";

interface Props {
  data: AnalyticsData;
}

function alphaColor(alpha: number): string {
  if (alpha >= 0.8) return "#10B981";
  if (alpha >= 0.667) return "#4ECDC4";
  if (alpha >= 0.4) return "#F59E0B";
  return "#F43F5E";
}

function alphaLabel(alpha: number, nEvaluators: number): string {
  if (nEvaluators < 2) return "Requiere 2+ evaluadores";
  if (alpha >= 0.8) return "Excelente";
  if (alpha >= 0.667) return "Aceptable";
  if (alpha >= 0.4) return "Moderada";
  return "Baja";
}

function agreementBg(value: number): string {
  const r = Math.round(255 * (1 - value));
  const g = Math.round(200 * value);
  const b = Math.round(140 * value);
  return `rgba(${r}, ${g}, ${b}, 0.3)`;
}

export function InterRaterReliability({ data }: Props) {
  const { interRater, evaluators } = data;
  const nEvaluators = evaluators.length;

  const globalAlpha = interRater.krippendorffAlpha;

  const questionAlphaEntries = useMemo(
    () => Object.entries(interRater.alphaPerQuestion).sort(([a], [b]) => a.localeCompare(b)),
    [interRater.alphaPerQuestion]
  );

  const typeAlphaEntries = useMemo(
    () => Object.entries(interRater.alphaPerQuestionType),
    [interRater.alphaPerQuestionType]
  );

  const evaluatorNames: Record<string, string> = useMemo(() => {
    const m: Record<string, string> = {};
    for (const ev of evaluators) m[ev.id] = ev.name;
    return m;
  }, [evaluators]);

  if (nEvaluators < 2) {
    return (
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-3">
          <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0" />
          <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
            Fiabilidad inter-evaluador
          </h3>
        </div>
        <p className="text-sm text-surface-500 italic">
          Se requieren al menos 2 evaluadores para calcular la fiabilidad.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Global alpha hero */}
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-violet-400 shrink-0" />
          <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
            Alpha de Krippendorff global
          </h3>
        </div>
        <div className="flex items-end gap-4">
          <span
            className="font-serif text-5xl font-semibold tabular-nums leading-none"
            style={{ color: alphaColor(globalAlpha) }}
          >
            {globalAlpha.toFixed(3)}
          </span>
          <div className="pb-1">
            <span
              className="text-sm font-semibold"
              style={{ color: alphaColor(globalAlpha) }}
            >
              {alphaLabel(globalAlpha, nEvaluators)}
            </span>
            <p className="text-xs text-surface-500 mt-0.5">
              Escala intervalo · {nEvaluators} evaluadores
            </p>
          </div>
        </div>
        {/* Alpha bar */}
        <div className="mt-4 h-1.5 bg-surface-800 rounded-full overflow-hidden">
          <div
            className="h-1.5 rounded-full transition-all duration-700"
            style={{
              width: `${Math.max(0, Math.min(100, globalAlpha * 100))}%`,
              backgroundColor: alphaColor(globalAlpha),
            }}
          />
        </div>
        <div className="flex justify-between text-[10px] text-surface-600 mt-1">
          <span>0</span>
          <span>0.4</span>
          <span>0.667</span>
          <span>0.8</span>
          <span>1</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        {/* Per-question alpha */}
        {questionAlphaEntries.length > 0 && (
          <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
            <div className="flex items-center gap-2 mb-4">
              <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 shrink-0" />
              <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
                Alpha por pregunta
              </h3>
            </div>
            <div className="space-y-3">
              {questionAlphaEntries.map(([qId, alpha]) => (
                <div key={qId}>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-xs font-mono text-surface-400">Q{qId}</span>
                    <span
                      className="text-xs font-semibold tabular-nums"
                      style={{ color: alphaColor(alpha) }}
                    >
                      {alpha.toFixed(3)}
                    </span>
                  </div>
                  <div className="h-1 bg-surface-800 rounded-full overflow-hidden">
                    <div
                      className="h-1 rounded-full"
                      style={{
                        width: `${Math.max(0, Math.min(100, alpha * 100))}%`,
                        backgroundColor: alphaColor(alpha),
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Per-type alpha */}
        {typeAlphaEntries.length > 0 && (
          <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
            <div className="flex items-center gap-2 mb-4">
              <span className="w-1.5 h-1.5 rounded-full bg-teal-400 shrink-0" />
              <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
                Alpha por tipo
              </h3>
            </div>
            <div className="space-y-3">
              {typeAlphaEntries.map(([type, alpha]) => (
                <div key={type}>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-xs font-medium text-surface-400 capitalize">
                      {type}
                    </span>
                    <span
                      className="text-xs font-semibold tabular-nums"
                      style={{ color: alphaColor(alpha) }}
                    >
                      {alpha.toFixed(3)}
                    </span>
                  </div>
                  <div className="h-1 bg-surface-800 rounded-full overflow-hidden">
                    <div
                      className="h-1 rounded-full"
                      style={{
                        width: `${Math.max(0, Math.min(100, alpha * 100))}%`,
                        backgroundColor: alphaColor(alpha),
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Pairwise agreement heatmap */}
      {interRater.pairwiseAgreement.length > 0 && (
        <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
          <div className="flex items-center gap-2 mb-4">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0" />
            <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
              Acuerdo pairwise (% exacto)
            </h3>
          </div>
          <div className="overflow-x-auto">
            <table className="text-xs">
              <thead>
                <tr>
                  <th className="p-2" />
                  {evaluators.map((ev) => (
                    <th key={ev.id} className="p-2 text-surface-400 font-medium text-center">
                      {ev.name}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {evaluators.map((ev1) => (
                  <tr key={ev1.id}>
                    <td className="p-2 text-surface-400 font-medium pr-4">{ev1.name}</td>
                    {evaluators.map((ev2) => {
                      if (ev1.id === ev2.id) {
                        return (
                          <td
                            key={ev2.id}
                            className="p-2 text-center"
                            style={{ backgroundColor: "rgba(255,255,255,0.04)" }}
                          >
                            <span className="text-surface-600">—</span>
                          </td>
                        );
                      }
                      const pair = interRater.pairwiseAgreement.find(
                        (p) =>
                          (p.evaluator1 === ev1.id && p.evaluator2 === ev2.id) ||
                          (p.evaluator1 === ev2.id && p.evaluator2 === ev1.id)
                      );
                      const agreement = pair?.agreement ?? 0;
                      return (
                        <td
                          key={ev2.id}
                          className="p-2 text-center tabular-nums font-mono"
                          style={{ backgroundColor: agreementBg(agreement) }}
                        >
                          <span className="text-surface-200">
                            {(agreement * 100).toFixed(0)}%
                          </span>
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
