// src/components/admin/ModelDrilldown.svelte
<script lang="ts">
  import type { ModelStats, AnalyticsData } from '../../lib/analytics';
  import ChartCanvas from './ChartCanvas.svelte';

  interface Props {
    model: ModelStats;
    data: AnalyticsData;
    onClose: () => void;
  }

  let { model, data, onClose }: Props = $props();

  const questionLabels: Record<string, string> = {
    '1': 'Q1: Tipo de notación',
    '2': 'Q2: Tonalidad',
    '3': 'Q3: Instrumento',
  };

  // Per-image scores for this model
  const imageScores = $derived(
    data.images.map(img => ({
      filename: img.imageFilename,
      score: img.modelScores[model.modelName] ?? 0,
      questionScores: Object.entries(img.questionScores).map(([qId, models]) => ({
        questionId: qId,
        label: questionLabels[qId] || `Q${qId}`,
        score: models[model.modelName] ?? 0,
      })),
    })).sort((a, b) => b.score - a.score)
  );

  // Radar chart: score per question type
  const radarData = $derived(() => {
    const labels = Object.entries(model.questionStats).map(([qId]) => questionLabels[qId] || `Q${qId}`);
    const scores = Object.values(model.questionStats).map(qs => qs.mean);
    return {
      labels,
      datasets: [{
        label: model.shortName,
        data: scores,
        backgroundColor: 'rgba(79, 70, 229, 0.2)',
        borderColor: '#4F46E5',
        borderWidth: 2,
        pointBackgroundColor: '#4F46E5',
        pointRadius: 4,
      }],
    };
  });

  const radarOptions = {
    scales: {
      r: {
        beginAtZero: true,
        max: 5,
        ticks: { stepSize: 1, color: '#64748B', font: { size: 10 }, backdropColor: 'transparent' },
        grid: { color: 'rgba(203, 213, 225, 0.3)' },
        pointLabels: { color: '#334155', font: { size: 12 } },
        angleLines: { color: 'rgba(203, 213, 225, 0.3)' },
      },
    },
    plugins: {
      legend: { display: false },
    },
  };

  // Strengths and weaknesses
  const sortedQuestions = $derived(
    Object.entries(model.questionStats)
      .map(([qId, qs]) => ({ qId, label: questionLabels[qId] || `Q${qId}`, ...qs }))
      .sort((a, b) => b.mean - a.mean)
  );

  const bestQuestion = $derived(sortedQuestions[0]);
  const worstQuestion = $derived(sortedQuestions[sortedQuestions.length - 1]);
</script>

<!-- Overlay backdrop -->
<div class="fixed inset-0 z-50 flex items-start justify-center pt-8 pb-8 overflow-y-auto"
     onclick={(e) => { if (e.target === e.currentTarget) onClose(); }}>
  <div class="bg-surface-950 border border-surface-700 rounded-xl shadow-2xl w-full max-w-4xl mx-4 card-elevated">

    <!-- Header -->
    <div class="px-6 py-5 border-b border-surface-700 flex items-center justify-between">
      <div>
        <h2 class="font-serif text-xl font-semibold text-surface-100">{model.shortName}</h2>
        <span class="text-sm text-surface-500">{model.provider} — {model.modelName}</span>
      </div>
      <button onclick={onClose}
              class="w-8 h-8 flex items-center justify-center rounded-lg hover:bg-surface-850 text-surface-500 hover:text-surface-300 transition-colors cursor-pointer">
        <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Stats grid -->
    <div class="px-6 py-5 grid grid-cols-2 sm:grid-cols-4 gap-4 border-b border-surface-700/50">
      <div>
        <span class="text-xs text-surface-500 uppercase tracking-widest">Accuracy</span>
        <div class="text-2xl font-serif font-semibold text-surface-100 tabular-nums mt-1">
          {(model.binaryAccuracy * 100).toFixed(0)}%
        </div>
        <span class="text-xs text-surface-500">{model.binaryCorrect}/{model.binaryTotal}</span>
      </div>
      <div>
        <span class="text-xs text-surface-500 uppercase tracking-widest">Score ranking</span>
        <div class="text-2xl font-serif font-semibold text-surface-100 tabular-nums mt-1">
          {model.meanRankingScore.toFixed(2)}
        </div>
        <span class="text-xs text-surface-500">de 5.00</span>
      </div>
      <div>
        <span class="text-xs text-surface-500 uppercase tracking-widest">Tiempo medio</span>
        <div class="text-2xl font-serif font-semibold text-surface-100 tabular-nums mt-1">
          {model.avgResponseTime.toFixed(1)}s
        </div>
        <span class="text-xs text-surface-500">{model.responseTimes.length} respuestas</span>
      </div>
      <div>
        <span class="text-xs text-surface-500 uppercase tracking-widest">Compuesto</span>
        <div class="text-2xl font-serif font-semibold text-accent-600 tabular-nums mt-1">
          {(model.compositeScore * 100).toFixed(1)}
        </div>
        <span class="text-xs text-surface-500">{model.totalEvaluations} evaluaciones</span>
      </div>
    </div>

    <!-- Content -->
    <div class="p-6 space-y-6">

      <!-- Radar + Strengths -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <!-- Radar -->
        <div>
          <h4 class="text-sm font-medium text-surface-300 mb-3">Perfil por pregunta</h4>
          {#if Object.keys(model.questionStats).length > 0}
            <ChartCanvas type="radar" data={radarData()} options={radarOptions} height="240px" />
          {:else}
            <div class="py-8 text-center text-surface-500 text-sm italic">Sin datos</div>
          {/if}
        </div>

        <!-- Strengths / Weaknesses -->
        <div class="space-y-4">
          <h4 class="text-sm font-medium text-surface-300">Fortalezas y Debilidades</h4>

          {#if bestQuestion}
            <div class="bg-emerald-50 border border-emerald-200 rounded-lg p-3">
              <div class="flex items-center gap-2 mb-1">
                <svg class="w-4 h-4 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 10.5 12 3m0 0 7.5 7.5M12 3v18" />
                </svg>
                <span class="text-xs font-medium text-emerald-700 uppercase tracking-widest">Mejor rendimiento</span>
              </div>
              <span class="text-sm text-emerald-800 font-medium">{bestQuestion.label}</span>
              <span class="text-sm text-emerald-600 ml-2">— {bestQuestion.mean.toFixed(2)}/5</span>
            </div>
          {/if}

          {#if worstQuestion && worstQuestion.qId !== bestQuestion?.qId}
            <div class="bg-amber-50 border border-amber-200 rounded-lg p-3">
              <div class="flex items-center gap-2 mb-1">
                <svg class="w-4 h-4 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5 12 21m0 0-7.5-7.5M12 21V3" />
                </svg>
                <span class="text-xs font-medium text-amber-700 uppercase tracking-widest">A mejorar</span>
              </div>
              <span class="text-sm text-amber-800 font-medium">{worstQuestion.label}</span>
              <span class="text-sm text-amber-600 ml-2">— {worstQuestion.mean.toFixed(2)}/5</span>
            </div>
          {/if}

          <!-- Per-question breakdown -->
          <div class="space-y-2">
            {#each sortedQuestions as q}
              <div class="flex items-center gap-3">
                <span class="text-xs text-surface-500 w-32 shrink-0">{q.label}</span>
                <div class="flex-1 h-2 bg-surface-800 rounded-full overflow-hidden">
                  <div class="h-full bg-accent-500 rounded-full" style="width: {(q.mean / 5) * 100}%"></div>
                </div>
                <span class="text-xs font-mono tabular-nums text-surface-400 w-10 text-right">{q.mean.toFixed(2)}</span>
              </div>
            {/each}
          </div>
        </div>
      </div>

      <!-- Per-image scores -->
      <div>
        <h4 class="text-sm font-medium text-surface-300 mb-3">Scores por Imagen</h4>
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="bg-surface-850">
                <th class="text-left px-4 py-2 text-xs font-medium text-surface-500 uppercase tracking-widest">Imagen</th>
                {#each imageScores[0]?.questionScores || [] as qs}
                  <th class="text-center px-3 py-2 text-xs font-medium text-surface-500 uppercase tracking-widest">{qs.label}</th>
                {/each}
                <th class="text-center px-3 py-2 text-xs font-medium text-surface-500 uppercase tracking-widest">Media</th>
              </tr>
            </thead>
            <tbody>
              {#each imageScores as img}
                <tr class="border-b border-surface-700/50">
                  <td class="px-4 py-2">
                    <span class="text-xs font-mono text-surface-400">{img.filename}</span>
                  </td>
                  {#each img.questionScores as qs}
                    <td class="px-3 py-2 text-center">
                      <span class="text-xs font-mono tabular-nums {qs.score >= 4 ? 'text-emerald-600' : qs.score >= 2.5 ? 'text-surface-300' : qs.score > 0 ? 'text-amber-600' : 'text-surface-600'}">
                        {qs.score > 0 ? qs.score.toFixed(1) : '—'}
                      </span>
                    </td>
                  {/each}
                  <td class="px-3 py-2 text-center">
                    <span class="text-xs font-mono font-semibold tabular-nums text-surface-200">
                      {img.score > 0 ? img.score.toFixed(1) : '—'}
                    </span>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

// src/components/react/admin/ModelDrilldown.tsx
import { useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  ResponsiveContainer,
  Tooltip,
} from "recharts";
import { TOOLTIP_STYLE, TOOLTIP_LABEL_STYLE, TOOLTIP_ITEM_STYLE } from "./charts/rechartsTheme";
import type { AnalyticsData, ModelStats } from "../../../lib/analytics";
import { costEfficiency, hasPricing } from "../../../lib/pricing";

interface Props {
  model: ModelStats;
  data: AnalyticsData;
  costData: { totalCost: number; efficiency: number | null };
  onClose: () => void;
}

export function ModelDrilldown({ model, data, costData, onClose }: Props) {
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.addEventListener("keydown", handleKey);
    return () => document.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const radarData = Object.entries(model.questionStats).map(([qId, qs]) => ({
    question: `Q${qId}`,
    score: parseFloat(qs.mean.toFixed(2)),
    fullMark: qs.type === "binary" ? 1 : 5,
  }));

  const strengths = Object.entries(model.questionStats)
    .filter(([, qs]) => qs.mean >= 3.5)
    .map(([qId, qs]) => ({ qId, text: qs.questionText, mean: qs.mean }));

  const weaknesses = Object.entries(model.questionStats)
    .filter(([, qs]) => qs.mean < 2)
    .map(([qId, qs]) => ({ qId, text: qs.questionText, mean: qs.mean }));

  const rank = data.models.findIndex((m) => m.modelName === model.modelName) + 1;

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        {/* Backdrop */}
        <motion.div
          className="absolute inset-0 bg-black/70 backdrop-blur-sm"
          onClick={onClose}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
        />

        {/* Panel */}
        <motion.div
          className="relative z-10 w-full max-w-2xl bg-surface-900 border border-surface-700 rounded-2xl overflow-hidden shadow-2xl"
          initial={{ scale: 0.95, y: 16, opacity: 0 }}
          animate={{ scale: 1, y: 0, opacity: 1 }}
          exit={{ scale: 0.95, y: 8, opacity: 0 }}
          transition={{ type: "spring", stiffness: 300, damping: 30 }}
        >
          {/* Header */}
          <div className="flex items-start justify-between p-5 border-b border-surface-700">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-medium text-surface-500 uppercase tracking-widest">
                  #{rank} · {model.provider}
                </span>
              </div>
              <h2 className="font-serif text-xl font-semibold text-surface-100">
                {model.shortName}
              </h2>
              <p className="text-xs text-surface-500 font-mono mt-0.5">{model.modelName}</p>
            </div>
            <button
              onClick={onClose}
              className="text-surface-500 hover:text-surface-300 transition-colors p-1 cursor-pointer"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Body */}
          <div className="p-5 space-y-5 max-h-[70vh] overflow-y-auto">
            {/* Stats row */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[
                { label: "Score comp.", value: (model.compositeScore * 100).toFixed(1), unit: "" },
                { label: "Accuracy", value: (model.binaryAccuracy * 100).toFixed(0), unit: "%" },
                { label: "Ranking", value: model.meanRankingScore.toFixed(2), unit: "/5" },
                { label: "Tiempo medio", value: model.avgResponseTime.toFixed(1), unit: "s" },
              ].map((stat) => (
                <div
                  key={stat.label}
                  className="bg-surface-800 border border-surface-700 rounded-lg p-3 text-center"
                >
                  <p className="text-[10px] text-surface-500 uppercase tracking-widest mb-1">{stat.label}</p>
                  <p className="font-serif text-lg font-semibold text-surface-100 tabular-nums">
                    {stat.value}
                    <span className="text-surface-500 text-sm">{stat.unit}</span>
                  </p>
                </div>
              ))}
            </div>

            {/* Radar chart */}
            {radarData.length > 0 && (
              <div>
                <p className="text-xs text-surface-500 uppercase tracking-widest mb-3">
                  Perfil por pregunta
                </p>
                <ResponsiveContainer width="100%" height={220}>
                  <RadarChart data={radarData} cx="50%" cy="50%" outerRadius={80}>
                    <PolarGrid stroke="rgba(255,255,255,0.07)" />
                    <PolarAngleAxis
                      dataKey="question"
                      tick={{ fill: "#9CA3AF", fontSize: 12 }}
                    />
                    <PolarRadiusAxis
                      angle={30}
                      domain={[0, 5]}
                      tick={{ fill: "#4A5170", fontSize: 10 }}
                    />
                    <Radar
                      name={model.shortName}
                      dataKey="score"
                      stroke="#C8A85A"
                      fill="#C8A85A"
                      fillOpacity={0.2}
                    />
                    <Tooltip
                      contentStyle={TOOLTIP_STYLE}
                      labelStyle={TOOLTIP_LABEL_STYLE}
                      itemStyle={TOOLTIP_ITEM_STYLE}
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </div>
            )}

            {/* Cost profile */}
            {hasPricing(model.modelName) && (
              <div className="bg-surface-800 border border-surface-700 rounded-lg p-4">
                <p className="text-xs text-surface-500 uppercase tracking-widest mb-3">
                  Perfil de coste
                </p>
                <div className="grid grid-cols-3 gap-3">
                  <div className="text-center">
                    <p className="text-[10px] text-surface-500 mb-1">Coste total</p>
                    <p className="font-mono text-sm font-semibold text-teal-400">
                      {costData.totalCost > 0 ? `$${costData.totalCost.toFixed(5)}` : "—"}
                    </p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] text-surface-500 mb-1">Score/USD</p>
                    <p className="font-mono text-sm font-semibold text-amber-400">
                      {costData.efficiency !== null ? costData.efficiency.toFixed(4) : "—"}
                    </p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] text-surface-500 mb-1">Rango global</p>
                    <p className="font-mono text-sm font-semibold text-surface-200">
                      #{rank} / {data.models.length}
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Strengths & weaknesses */}
            {(strengths.length > 0 || weaknesses.length > 0) && (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {strengths.length > 0 && (
                  <div>
                    <p className="text-xs text-emerald-400 uppercase tracking-widest mb-2">
                      Fortalezas
                    </p>
                    {strengths.map(({ qId, text, mean }) => (
                      <div key={qId} className="flex items-start gap-2 mb-2">
                        <span className="text-emerald-400 mt-0.5 text-xs">✓</span>
                        <div>
                          <p className="text-xs text-surface-300 leading-snug">
                            {text.length > 50 ? text.slice(0, 50) + "…" : text}
                          </p>
                          <p className="text-[10px] text-emerald-500">{mean.toFixed(2)} / 5</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
                {weaknesses.length > 0 && (
                  <div>
                    <p className="text-xs text-rose-400 uppercase tracking-widest mb-2">
                      Debilidades
                    </p>
                    {weaknesses.map(({ qId, text, mean }) => (
                      <div key={qId} className="flex items-start gap-2 mb-2">
                        <span className="text-rose-400 mt-0.5 text-xs">✗</span>
                        <div>
                          <p className="text-xs text-surface-300 leading-snug">
                            {text.length > 50 ? text.slice(0, 50) + "…" : text}
                          </p>
                          <p className="text-[10px] text-rose-500">{mean.toFixed(2)} / 5</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
