// src/components/admin/ScoreDistribution.svelte
<script lang="ts">
  import type { AnalyticsData } from '../../lib/analytics';
  import { shortModelName } from '../../lib/analytics';
  import ChartCanvas from './ChartCanvas.svelte';

  interface Props {
    data: AnalyticsData;
  }

  let { data }: Props = $props();

  const modelColors = [
    { bg: 'rgba(79, 70, 229, 0.5)', border: '#4F46E5' },
    { bg: 'rgba(245, 158, 11, 0.5)', border: '#F59E0B' },
    { bg: 'rgba(16, 185, 129, 0.5)', border: '#10B981' },
    { bg: 'rgba(239, 68, 68, 0.5)', border: '#EF4444' },
    { bg: 'rgba(139, 92, 246, 0.5)', border: '#8B5CF6' },
    { bg: 'rgba(6, 182, 212, 0.5)', border: '#06B6D4' },
    { bg: 'rgba(244, 63, 94, 0.5)', border: '#F43F5E' },
    { bg: 'rgba(34, 197, 94, 0.5)', border: '#22C55E' },
  ];

  // Ranking score distribution (0-5 buckets)
  const rankingChartData = $derived(() => {
    const labels = ['0', '1', '2', '3', '4', '5'];
    const datasets = data.models.map((model, i) => {
      const color = modelColors[i % modelColors.length];
      const buckets = new Array(6).fill(0);
      for (const score of model.rankingScores) {
        const bucket = Math.min(5, Math.max(0, Math.round(score)));
        buckets[bucket]++;
      }
      return {
        label: model.shortName,
        data: buckets,
        backgroundColor: color.bg,
        borderColor: color.border,
        borderWidth: 1.5,
        borderRadius: 3,
      };
    });
    return { labels, datasets };
  });

  const rankingOptions = {
    plugins: {
      legend: { position: 'bottom' as const },
      title: { display: true, text: 'Distribución de scores ranking (0-5)', color: '#334155', font: { size: 13, family: "'Crimson Pro', serif" } },
    },
    scales: {
      x: { title: { display: true, text: 'Score', color: '#64748B', font: { size: 11 } } },
      y: { beginAtZero: true, title: { display: true, text: 'Frecuencia', color: '#64748B', font: { size: 11 } } },
    },
  };

  // Binary accuracy (stacked bar)
  const binaryChartData = $derived(() => {
    const labels = data.models.map(m => m.shortName);
    return {
      labels,
      datasets: [
        {
          label: 'Correcto',
          data: data.models.map(m => m.binaryCorrect),
          backgroundColor: 'rgba(16, 185, 129, 0.6)',
          borderColor: '#10B981',
          borderWidth: 1.5,
          borderRadius: 3,
        },
        {
          label: 'Incorrecto',
          data: data.models.map(m => m.binaryTotal - m.binaryCorrect),
          backgroundColor: 'rgba(239, 68, 68, 0.5)',
          borderColor: '#EF4444',
          borderWidth: 1.5,
          borderRadius: 3,
        },
      ],
    };
  });

  const binaryOptions = {
    plugins: {
      legend: { position: 'bottom' as const },
      title: { display: true, text: 'Evaluaciones binarias: Correcto vs Incorrecto', color: '#334155', font: { size: 13, family: "'Crimson Pro', serif" } },
    },
    scales: {
      x: { stacked: true },
      y: { stacked: true, beginAtZero: true, title: { display: true, text: 'Cantidad', color: '#64748B', font: { size: 11 } } },
    },
  };
</script>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
  <!-- Ranking distribution -->
  <div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
    <div class="p-5">
      {#if data.models.some(m => m.rankingScores.length > 0)}
        <ChartCanvas type="bar" data={rankingChartData()} options={rankingOptions} height="280px" />
      {:else}
        <div class="py-12 text-center text-surface-500 font-serif italic">Sin datos de ranking</div>
      {/if}
    </div>
  </div>

  <!-- Binary accuracy -->
  <div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
    <div class="p-5">
      {#if data.models.some(m => m.binaryTotal > 0)}
        <ChartCanvas type="bar" data={binaryChartData()} options={binaryOptions} height="280px" />
      {:else}
        <div class="py-12 text-center text-surface-500 font-serif italic">Sin datos binarios</div>
      {/if}
    </div>
  </div>
</div>

// src/components/react/admin/ScoreDistribution.tsx
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import {
  CHART_COLORS,
  COMMON_AXIS_PROPS,
  COMMON_CARTESIAN_GRID,
  TOOLTIP_STYLE,
  TOOLTIP_LABEL_STYLE,
  TOOLTIP_ITEM_STYLE,
  LEGEND_STYLE,
} from "./charts/rechartsTheme";
import type { AnalyticsData } from "../../../lib/analytics";

interface Props {
  data: AnalyticsData;
}

export function ScoreDistribution({ data }: Props) {
  // Ranking score histogram — buckets 0..5
  const buckets = [0, 1, 2, 3, 4, 5];
  const rankingData = buckets.map((bucket) => {
    const row: Record<string, number | string> = { score: String(bucket) };
    for (const model of data.models) {
      row[model.shortName] = model.rankingScores.filter((s) => Math.round(s) === bucket).length;
    }
    return row;
  });

  // Binary accuracy stacked bar
  const binaryData = data.models.map((model, i) => ({
    name: model.shortName,
    Correctas: model.binaryCorrect,
    Incorrectas: model.binaryTotal - model.binaryCorrect,
    color: CHART_COLORS[i % CHART_COLORS.length],
  }));

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
      {/* Ranking histogram */}
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />
          <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
            Distribución ranking
          </h3>
        </div>
        <ResponsiveContainer width="100%" height={240}>
          <BarChart data={rankingData} margin={{ top: 0, right: 10, left: -10, bottom: 0 }}>
            <CartesianGrid {...COMMON_CARTESIAN_GRID} vertical={false} />
            <XAxis dataKey="score" {...COMMON_AXIS_PROPS} />
            <YAxis {...COMMON_AXIS_PROPS} />
            <Tooltip
              contentStyle={TOOLTIP_STYLE}
              labelStyle={TOOLTIP_LABEL_STYLE}
              itemStyle={TOOLTIP_ITEM_STYLE}
              labelFormatter={(v) => `Score ${v}`}
            />
            <Legend wrapperStyle={LEGEND_STYLE} />
            {data.models.map((model, i) => (
              <Bar
                key={model.modelName}
                dataKey={model.shortName}
                fill={CHART_COLORS[i % CHART_COLORS.length]}
                radius={[3, 3, 0, 0]}
                maxBarSize={24}
              />
            ))}
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Binary accuracy stacked */}
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0" />
          <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
            Accuracy binaria por modelo
          </h3>
        </div>
        <ResponsiveContainer width="100%" height={240}>
          <BarChart
            data={binaryData}
            layout="vertical"
            margin={{ top: 0, right: 10, left: 8, bottom: 0 }}
          >
            <CartesianGrid {...COMMON_CARTESIAN_GRID} horizontal={false} />
            <XAxis type="number" {...COMMON_AXIS_PROPS} />
            <YAxis
              type="category"
              dataKey="name"
              width={90}
              {...COMMON_AXIS_PROPS}
            />
            <Tooltip
              contentStyle={TOOLTIP_STYLE}
              labelStyle={TOOLTIP_LABEL_STYLE}
              itemStyle={TOOLTIP_ITEM_STYLE}
            />
            <Legend wrapperStyle={LEGEND_STYLE} />
            <Bar dataKey="Correctas" stackId="binary" fill="#10B981" radius={[0, 3, 3, 0]} />
            <Bar dataKey="Incorrectas" stackId="binary" fill="#F43F5E" radius={[0, 3, 3, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
