// src/components/react/admin/EvaluatorActivity.tsx
import type { AnalyticsData } from "../../../lib/analytics";

interface Props {
  data: AnalyticsData;
  totalPerEvaluator: number;
}

function timeSince(dateStr: string | null): string {
  if (!dateStr) return "Sin actividad";
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `hace ${mins}m`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `hace ${hours}h`;
  const days = Math.floor(hours / 24);
  return `hace ${days}d`;
}

function biasColor(bias: number): string {
  if (Math.abs(bias) < 0.1) return "text-surface-400";
  if (bias > 0) return "text-emerald-400";
  return "text-rose-400";
}

export function EvaluatorActivity({ data, totalPerEvaluator }: Props) {
  if (data.evaluators.length === 0) {
    return (
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <p className="text-sm text-surface-500 italic">Sin datos de evaluadores.</p>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Summary table */}
      <div className="bg-surface-900 border border-surface-700 rounded-xl p-5 card-elevated">
        <div className="flex items-center gap-2 mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0" />
          <h3 className="text-sm font-semibold text-surface-200 uppercase tracking-widest">
            Actividad por evaluador
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-surface-700">
                {["Evaluador", "Progreso", "Completadas", "Score medio", "Desv. estándar", "Sesgo", "Última actividad"].map((h) => (
                  <th
                    key={h}
                    className="py-2 px-3 text-left text-surface-500 font-medium uppercase tracking-widest"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.evaluators.map((ev, i) => {
                const pct =
                  totalPerEvaluator > 0
                    ? Math.round((ev.completed / totalPerEvaluator) * 100)
                    : 0;
                return (
                  <tr
                    key={ev.id}
                    className="border-b border-surface-800 hover:bg-surface-800/40 transition-colors"
                  >
                    <td className="py-3 px-3">
                      <span className="font-medium text-surface-200">{ev.name}</span>
                    </td>
                    <td className="py-3 px-3 w-40">
                      <div className="flex items-center gap-2">
                        <div className="flex-1 h-1.5 bg-surface-800 rounded-full overflow-hidden">
                          <div
                            className="h-1.5 rounded-full bg-amber-500"
                            style={{ width: `${pct}%` }}
                          />
                        </div>
                        <span className="text-surface-400 tabular-nums w-8 text-right">
                          {pct}%
                        </span>
                      </div>
                    </td>
                    <td className="py-3 px-3 text-surface-400 tabular-nums">
                      {ev.completed} / {totalPerEvaluator}
                    </td>
                    <td className="py-3 px-3 text-surface-300 tabular-nums font-mono">
                      {ev.meanScore.toFixed(2)}
                    </td>
                    <td className="py-3 px-3 text-surface-400 tabular-nums font-mono">
                      {ev.stdDev.toFixed(2)}
                    </td>
                    <td className={`py-3 px-3 tabular-nums font-mono font-semibold ${biasColor(ev.bias)}`}>
                      {ev.bias >= 0 ? "+" : ""}{ev.bias.toFixed(2)}
                    </td>
                    <td className="py-3 px-3 text-surface-500">
                      {timeSince(ev.lastActivity)}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Score distribution per evaluator */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {data.evaluators.map((ev) => {
          const total = ev.scoreDistribution.reduce((a, b) => a + b, 0);
          return (
            <div
              key={ev.id}
              className="bg-surface-900 border border-surface-700 rounded-xl p-4 card-elevated"
            >
              <p className="text-xs font-semibold text-surface-300 mb-3">{ev.name}</p>
              <div className="flex items-end gap-1 h-16">
                {ev.scoreDistribution.map((count, bucket) => {
                  const pct = total > 0 ? (count / total) * 100 : 0;
                  const colors = [
                    "#F43F5E", "#F59E0B", "#EAB308", "#4ECDC4", "#10B981", "#C8A85A",
                  ];
                  return (
                    <div
                      key={bucket}
                      className="flex-1 flex flex-col items-center gap-1"
                    >
                      <div
                        className="w-full rounded-t-sm transition-all"
                        style={{
                          height: `${Math.max(2, pct)}%`,
                          backgroundColor: colors[bucket],
                          opacity: pct > 0 ? 0.85 : 0.2,
                        }}
                      />
                      <span className="text-[9px] text-surface-600">{bucket}</span>
                    </div>
                  );
                })}
              </div>
              <p className="text-[10px] text-surface-600 mt-2">
                {total} evaluaciones · sesgo {ev.bias >= 0 ? "+" : ""}{ev.bias.toFixed(2)}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// src/components/admin/EvaluatorActivity.svelte
<script lang="ts">
  import type { AnalyticsData } from '../../lib/analytics';
  import ProgressBar from '../ProgressBar.svelte';

  interface Props {
    data: AnalyticsData;
    totalPerEvaluator: number;
  }

  let { data, totalPerEvaluator }: Props = $props();

  function formatDate(dateStr: string | null): string {
    if (!dateStr) return 'Sin actividad';
    const d = new Date(dateStr);
    return d.toLocaleDateString('es-ES', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  }

  function timeSince(dateStr: string | null): string {
    if (!dateStr) return '';
    const d = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - d.getTime();
    const diffMin = Math.floor(diffMs / 60000);
    if (diffMin < 60) return `hace ${diffMin}m`;
    const diffHours = Math.floor(diffMin / 60);
    if (diffHours < 24) return `hace ${diffHours}h`;
    const diffDays = Math.floor(diffHours / 24);
    return `hace ${diffDays}d`;
  }

  function biasLabel(bias: number): { text: string; class: string } {
    const abs = Math.abs(bias);
    if (abs < 0.3) return { text: 'Neutral', class: 'text-emerald-600 bg-emerald-50' };
    if (bias > 0) return { text: 'Generoso', class: 'text-accent-600 bg-accent-50' };
    return { text: 'Exigente', class: 'text-amber-600 bg-amber-50' };
  }
</script>

<div class="bg-surface-900 border border-surface-700 rounded-lg overflow-hidden card-elevated">
  <div class="px-5 py-4 border-b border-surface-700/50 flex items-center justify-between">
    <div>
      <h3 class="font-serif text-base font-semibold text-surface-100">Actividad de Evaluadores</h3>
      <p class="text-xs text-surface-500 mt-1">{totalPerEvaluator} evaluaciones requeridas por evaluador</p>
    </div>
    <div class="text-xs text-surface-500 tabular-nums">
      {data.evaluators.length} evaluador{data.evaluators.length !== 1 ? 'es' : ''}
    </div>
  </div>

  {#if data.evaluators.length > 0}
    <div class="overflow-x-auto">
      <table class="w-full">
        <thead>
          <tr class="bg-surface-850">
            <th class="text-left px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">Evaluador</th>
            <th class="text-left px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest w-40">Progreso</th>
            <th class="text-right px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">Completadas</th>
            <th class="text-right px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">%</th>
            <th class="text-right px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">Score medio</th>
            <th class="text-center px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">Tendencia</th>
            <th class="text-right px-5 py-3 text-xs font-medium text-surface-500 uppercase tracking-widest">Última actividad</th>
          </tr>
        </thead>
        <tbody>
          {#each data.evaluators as evaluator}
            {@const pct = totalPerEvaluator > 0 ? Math.round((evaluator.completed / totalPerEvaluator) * 100) : 0}
            {@const bl = biasLabel(evaluator.bias)}
            <tr class="border-b border-surface-700/50 hover:bg-surface-850/60 transition-colors">
              <td class="px-5 py-3.5">
                <span class="text-sm font-medium text-surface-100">{evaluator.name}</span>
              </td>
              <td class="px-5 py-3.5">
                <ProgressBar completed={evaluator.completed} total={totalPerEvaluator} size="sm" showLabel={false} />
              </td>
              <td class="px-5 py-3.5 text-right">
                <span class="text-sm text-surface-400 tabular-nums font-mono">{evaluator.completed}/{totalPerEvaluator}</span>
              </td>
              <td class="px-5 py-3.5 text-right">
                <span class="text-sm font-semibold tabular-nums {pct === 100 ? 'text-emerald-500' : pct > 50 ? 'text-accent-600' : 'text-surface-500'}">
                  {pct}%
                </span>
              </td>
              <td class="px-5 py-3.5 text-right">
                {#if evaluator.completed > 0}
                  <span class="text-sm font-mono tabular-nums text-surface-300">{evaluator.meanScore.toFixed(2)}</span>
                  <span class="text-xs text-surface-600 ml-1">±{evaluator.stdDev.toFixed(1)}</span>
                {:else}
                  <span class="text-sm text-surface-600">—</span>
                {/if}
              </td>
              <td class="px-5 py-3.5 text-center">
                {#if evaluator.completed > 0}
                  <span class="text-xs font-medium px-2 py-0.5 rounded {bl.class}">{bl.text}</span>
                {:else}
                  <span class="text-xs text-surface-600">—</span>
                {/if}
              </td>
              <td class="px-5 py-3.5 text-right">
                <div class="flex flex-col items-end">
                  <span class="text-xs text-surface-500 font-mono">{formatDate(evaluator.lastActivity)}</span>
                  {#if evaluator.lastActivity}
                    <span class="text-xs text-surface-600">{timeSince(evaluator.lastActivity)}</span>
                  {/if}
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {:else}
    <div class="px-5 py-12 text-center text-surface-500 font-serif italic">
      No hay evaluadores registrados
    </div>
  {/if}
</div>
