// src/components/react/Dashboard.tsx
import { useState, useEffect, useMemo } from "react";
import { motion } from "framer-motion";
import { validateEvaluatorKey, getEvaluations } from "../../lib/supabase";
import {
  countTotalEvaluations,
  getImageList,
  countImageEvaluations,
} from "../../lib/responses";
import { useAppStore } from "../../lib/store";
import { BlurFade } from "../magicui/blur-fade";
import { MagicCard } from "../magicui/magic-card";
import { ShimmerButton } from "../magicui/shimmer-button";
import { NumberTicker } from "../magicui/number-ticker";
import { AnimatedShinyText } from "../magicui/animated-shiny-text";
import type { ResponsesData, Evaluator, Evaluation } from "../../lib/types";
import { cn } from "../../lib/cn";

export function Dashboard() {
  const [loading, setLoading] = useState(true);
  const [evalData, setEvalData] = useState<Evaluator | null>(null);
  const [responses, setResponses] = useState<ResponsesData | null>(null);
  const [userEvaluations, setUserEvaluations] = useState<Evaluation[]>([]);

  const { setCurrentEvaluator, setEvaluations, setResponsesData } = useAppStore();

  const totalRequired = useMemo(
    () => (responses ? countTotalEvaluations(responses) : 0),
    [responses]
  );
  const totalCompleted = userEvaluations.length;
  const images = useMemo(
    () => (responses ? getImageList(responses) : []),
    [responses]
  );
  const percentage = useMemo(
    () => totalRequired > 0 ? Math.round((totalCompleted / totalRequired) * 100) : 0,
    [totalCompleted, totalRequired]
  );

  function getImageProgress(imageFilename: string) {
    if (!responses) return { completed: 0, total: 0 };
    const total = countImageEvaluations(responses, imageFilename);
    const completed = userEvaluations.filter(
      (e) => e.image_filename === imageFilename
    ).length;
    return { completed, total };
  }

  function getImageStatus(imageFilename: string): "none" | "partial" | "done" {
    const { completed, total } = getImageProgress(imageFilename);
    if (completed === 0) return "none";
    if (completed >= total) return "done";
    return "partial";
  }

  const countDone = useMemo(
    () => images.filter((img) => getImageStatus(img) === "done").length,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [images, userEvaluations]
  );
  const countPartial = useMemo(
    () => images.filter((img) => getImageStatus(img) === "partial").length,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [images, userEvaluations]
  );
  const countNone = useMemo(
    () => images.filter((img) => getImageStatus(img) === "none").length,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [images, userEvaluations]
  );

  const firstIncomplete = useMemo(
    () => images.find((img) => getImageStatus(img) !== "done") || null,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [images, userEvaluations]
  );

  useEffect(() => {
    async function init() {
      const key = localStorage.getItem("evaluator_key");
      if (!key) { window.location.href = "/login"; return; }

      const evaluator = await validateEvaluatorKey(key);
      if (!evaluator) {
        localStorage.removeItem("evaluator_key");
        window.location.href = "/login";
        return;
      }

      setEvalData(evaluator);
      setCurrentEvaluator(evaluator);

      const [responsesRes, evals] = await Promise.all([
        fetch("/api/responses").then((r) => r.json()),
        getEvaluations(evaluator.id),
      ]);

      setResponses(responsesRes as ResponsesData);
      setResponsesData(responsesRes);
      setUserEvaluations(evals);
      setEvaluations(evals);
      setLoading(false);
    }
    init();
  }, [setCurrentEvaluator, setEvaluations, setResponsesData]);

  function handleLogout() {
    localStorage.removeItem("evaluator_key");
    setCurrentEvaluator(null);
    window.location.href = "/login";
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-surface-950">
        <motion.div
          animate={{ opacity: [0.4, 1, 0.4] }}
          transition={{ duration: 1.8, repeat: Infinity, ease: "easeInOut" }}
          className="text-surface-400 text-sm font-serif italic"
        >
          Cargando...
        </motion.div>
      </div>
    );
  }

  if (!evalData || !responses) return null;

  return (
    <div className="min-h-screen bg-surface-950">
      {/* Header */}
      <header className="sticky top-0 z-20 bg-surface-900/95 backdrop-blur-sm border-b border-surface-700">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex items-center justify-center w-6 h-6 rounded bg-accent-600/10 border border-accent-500/20 shrink-0">
              <svg className="w-3.5 h-3.5 text-accent-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.75}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
              </svg>
            </div>
            <AnimatedShinyText shimmerWidth={120} className="font-serif text-[15px] font-semibold text-surface-100 tracking-tight">
              Music LLM Eval
            </AnimatedShinyText>
          </div>
          <div className="flex items-center gap-5">
            <span className="text-sm text-surface-400 hidden sm:inline">{evalData.name}</span>
            {evalData.is_admin && (
              <a href="/admin" className="text-xs text-accent-600 hover:text-accent-500 font-medium uppercase tracking-widest transition-colors">
                Admin
              </a>
            )}
            <button onClick={handleLogout} className="text-xs text-surface-500 hover:text-surface-300 cursor-pointer uppercase tracking-widest transition-colors">
              Salir
            </button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-10">
        {/* Progress hero */}
        <BlurFade delay={0.05} duration={0.5} inView>
          <MagicCard
            gradientColor="#4F46E5"
            gradientOpacity={0.08}
            className="bg-surface-900 border border-surface-700 rounded-xl overflow-hidden card-elevated mb-10"
          >
            <div className="p-7 flex flex-col sm:flex-row sm:items-start gap-6 sm:gap-10">
              {/* Big percentage */}
              <div className="shrink-0">
                <div className="font-serif text-6xl font-semibold text-surface-100 leading-none tabular-nums flex items-baseline gap-1">
                  <NumberTicker value={percentage} className="font-serif text-6xl font-semibold text-surface-100" />
                  <span className="text-3xl text-surface-400 ml-1">%</span>
                </div>
                <p className="text-sm text-surface-500 mt-2">
                  {totalCompleted} de {totalRequired} evaluaciones
                </p>
              </div>

              <div className="hidden sm:block w-px self-stretch bg-surface-700" />

              {/* Stats */}
              <div className="flex flex-col justify-center gap-3 flex-1">
                <div className="flex items-center gap-2.5">
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-green-500/15 shrink-0">
                    <svg className="w-3 h-3 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>
                  </div>
                  <span className="text-sm text-surface-300">
                    <NumberTicker value={countDone} className="font-medium tabular-nums text-surface-100" />{" "}
                    {countDone === 1 ? "partitura completa" : "partituras completas"}
                  </span>
                </div>
                <div className="flex items-center gap-2.5">
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-amber-400/15 shrink-0">
                    <svg className="w-3 h-3 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                    </svg>
                  </div>
                  <span className="text-sm text-surface-300">
                    <NumberTicker value={countPartial} className="font-medium tabular-nums text-surface-100" />{" "}
                    en progreso
                  </span>
                </div>
                <div className="flex items-center gap-2.5">
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-surface-700/50 shrink-0">
                    <svg className="w-3 h-3 text-surface-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 12h14" />
                    </svg>
                  </div>
                  <span className="text-sm text-surface-300">
                    <NumberTicker value={countNone} className="font-medium tabular-nums text-surface-100" />{" "}
                    sin empezar
                  </span>
                </div>
              </div>

              {/* CTA */}
              <div className="flex items-center sm:ml-auto">
                {firstIncomplete ? (
                  <ShimmerButton
                    onClick={() => { window.location.href = `/evaluate/${encodeURIComponent(firstIncomplete)}`; }}
                    background="rgba(79, 70, 229, 1)"
                    borderRadius="8px"
                    shimmerDuration="2.5s"
                    className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-semibold"
                  >
                    Continuar
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                    </svg>
                  </ShimmerButton>
                ) : (
                  <div className="inline-flex items-center gap-2 px-5 py-2.5 bg-green-500/10 border border-green-500/25 text-green-600 text-sm font-semibold rounded-lg">
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>
                    Completado
                  </div>
                )}
              </div>
            </div>

            {/* Full-width progress bar */}
            <div className="h-1 bg-surface-800">
              <motion.div
                className={cn("h-1", percentage === 100 ? "bg-green-500" : "bg-accent-600")}
                initial={{ width: 0 }}
                animate={{ width: `${percentage}%` }}
                transition={{ duration: 0.8, ease: "easeOut", delay: 0.2 }}
              />
            </div>
          </MagicCard>
        </BlurFade>

        {/* Bento grid header */}
        <BlurFade delay={0.15} duration={0.4} inView>
          <div className="flex items-center gap-3 mb-5">
            <h2 className="font-serif text-lg font-semibold text-surface-200 shrink-0">Partituras</h2>
            <span className="inline-flex items-center justify-center px-2 py-0.5 rounded-full bg-accent-100 text-accent-700 text-xs font-medium tabular-nums">
              {images.length}
            </span>
            <div className="flex-1 h-px bg-surface-700" />
            <div className="hidden sm:flex items-center gap-4 shrink-0">
              <span className="flex items-center gap-1.5 text-xs text-surface-500">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500" />Completas
              </span>
              <span className="flex items-center gap-1.5 text-xs text-surface-500">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-400" />En progreso
              </span>
            </div>
          </div>
        </BlurFade>

        {/* Cards grid */}
        <BlurFade delay={0.2} duration={0.5} inView>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3">
            {images.map((imageFilename, i) => {
              const progress = getImageProgress(imageFilename);
              const status = getImageStatus(imageFilename);
              const pct = progress.total > 0
                ? Math.round((progress.completed / progress.total) * 100)
                : 0;

              const borderColor = status === "done"
                ? "border-green-500/30 hover:border-green-500/50"
                : status === "partial"
                ? "border-amber-400/30 hover:border-amber-400/50"
                : "border-surface-700 hover:border-accent-500/30";

              const gradientColor = status === "done" ? "#10B981"
                : status === "partial" ? "#FBBF24"
                : "#4F46E5";

              return (
                <motion.a
                  key={imageFilename}
                  href={`/evaluate/${encodeURIComponent(imageFilename)}`}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.04, duration: 0.3, ease: "easeOut" }}
                  whileHover={{ y: -2 }}
                >
                  <MagicCard
                    gradientColor={gradientColor}
                    gradientOpacity={0.1}
                    className={cn(
                      "group h-full bg-surface-900 border rounded-xl overflow-hidden card-elevated flex flex-col",
                      borderColor
                    )}
                  >
                    {/* Thumbnail */}
                    <div className="relative flex-1 bg-surface-850 overflow-hidden flex items-center justify-center aspect-4/3">
                      <img
                        src={`/api/images/${imageFilename}`}
                        alt={imageFilename}
                        className={cn(
                          "w-full h-full object-contain p-3 transition-all duration-300 group-hover:scale-[1.02]",
                          status === "done" ? "opacity-75 group-hover:opacity-95" : "opacity-90 group-hover:opacity-100"
                        )}
                        loading="lazy"
                      />
                      {/* Status badge */}
                      {status === "done" && (
                        <div className="absolute top-2 right-2 flex items-center gap-1 px-1.5 py-0.5 bg-green-500/90 backdrop-blur-sm rounded-full">
                          <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                          </svg>
                          <span className="text-[10px] font-semibold text-white leading-none">Completa</span>
                        </div>
                      )}
                      {status === "partial" && (
                        <div className="absolute top-2 right-2 px-1.5 py-0.5 bg-amber-400/90 backdrop-blur-sm rounded-full">
                          <span className="text-[10px] font-semibold text-white leading-none">{progress.completed}/{progress.total}</span>
                        </div>
                      )}
                    </div>

                    {/* Footer */}
                    <div className={cn(
                      "shrink-0 border-t px-3 py-2",
                      status === "done" ? "border-green-500/20 bg-green-500/3"
                        : status === "partial" ? "border-amber-400/20 bg-amber-400/3"
                        : "border-surface-700"
                    )}>
                      <p className="text-[11px] font-mono text-surface-500 truncate leading-tight mb-1.5">
                        {imageFilename}
                      </p>
                      <div className="w-full h-0.5 bg-surface-800 rounded-full overflow-hidden">
                        <motion.div
                          className={cn("h-0.5 rounded-full", status === "done" ? "bg-green-500" : "bg-accent-600")}
                          initial={{ width: 0 }}
                          animate={{ width: `${pct}%` }}
                          transition={{ duration: 0.5, ease: "easeOut", delay: 0.1 + i * 0.02 }}
                        />
                      </div>
                    </div>
                  </MagicCard>
                </motion.a>
              );
            })}
          </div>
        </BlurFade>
      </main>
    </div>
  );
}

// src/components/Dashboard.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { currentEvaluator, evaluations, responsesData } from '../lib/stores';
  import { validateEvaluatorKey, getEvaluations } from '../lib/supabase';
  import { countTotalEvaluations, getImageList, countImageEvaluations } from '../lib/responses';
  import ProgressBar from './ProgressBar.svelte';
  import type { ResponsesData, Evaluator, Evaluation } from '../lib/types';

  let loading = $state(true);
  let evalData: Evaluator | null = $state(null);
  let responses: ResponsesData | null = $state(null);
  let userEvaluations: Evaluation[] = $state([]);

  let totalRequired = $derived(responses ? countTotalEvaluations(responses) : 0);
  let totalCompleted = $derived(userEvaluations.length);
  let images = $derived(responses ? getImageList(responses) : []);
  let percentage = $derived(totalRequired > 0 ? Math.round((totalCompleted / totalRequired) * 100) : 0);

  let countDone = $derived(images.filter((img) => getImageStatus(img) === 'done').length);
  let countPartial = $derived(images.filter((img) => getImageStatus(img) === 'partial').length);
  let countNone = $derived(images.filter((img) => getImageStatus(img) === 'none').length);

  function getImageProgress(imageFilename: string): { completed: number; total: number } {
    if (!responses) return { completed: 0, total: 0 };
    const total = countImageEvaluations(responses, imageFilename);
    const completed = userEvaluations.filter((e) => e.image_filename === imageFilename).length;
    return { completed, total };
  }

  function getImageStatus(imageFilename: string): 'none' | 'partial' | 'done' {
    const { completed, total } = getImageProgress(imageFilename);
    if (completed === 0) return 'none';
    if (completed >= total) return 'done';
    return 'partial';
  }

  let firstIncomplete = $derived(
    images.find((img) => getImageStatus(img) !== 'done') || null
  );

  onMount(async () => {
    const key = localStorage.getItem('evaluator_key');
    if (!key) { window.location.href = '/login'; return; }

    const evaluator = await validateEvaluatorKey(key);
    if (!evaluator) {
      localStorage.removeItem('evaluator_key');
      window.location.href = '/login';
      return;
    }

    evalData = evaluator;
    currentEvaluator.set(evaluator);

    const [responsesRes, evals] = await Promise.all([
      fetch('/api/responses').then((r) => r.json()),
      getEvaluations(evaluator.id),
    ]);

    responses = responsesRes as ResponsesData;
    responsesData.set(responses);
    userEvaluations = evals;
    evaluations.set(evals);
    loading = false;
  });

  function handleLogout() {
    localStorage.removeItem('evaluator_key');
    currentEvaluator.set(null);
    window.location.href = '/login';
  }
</script>

{#if loading}
  <div class="flex items-center justify-center min-h-screen bg-surface-950">
    <div class="text-surface-400 text-sm font-serif italic">Cargando...</div>
  </div>
{:else if evalData && responses}
  <div class="min-h-screen bg-surface-950">

    <!-- ── Header ──────────────────────────────────────────── -->
    <header class="sticky top-0 z-20 bg-surface-900/95 backdrop-blur-sm border-b border-surface-700">
      <div class="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
        <!-- Logo -->
        <div class="flex items-center gap-2.5">
          <svg class="w-4 h-4 text-accent-600 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 19V6l12-3v13M9 19c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zm12-3c0 1.105-1.343 2-3 2s-3-.895-3-2 1.343-2 3-2 3 .895 3 2zM9 10l12-3" />
          </svg>
          <span class="font-serif text-[15px] font-semibold text-surface-100 tracking-tight">Music LLM Eval</span>
        </div>

        <!-- Right side -->
        <div class="flex items-center gap-5">
          <span class="text-sm text-surface-400 hidden sm:inline">{evalData.name}</span>
          {#if evalData.is_admin}
            <a href="/admin"
               class="text-xs text-accent-600 hover:text-accent-500 font-medium uppercase tracking-widest transition-colors">
              Admin
            </a>
          {/if}
          <button
            onclick={handleLogout}
            class="text-xs text-surface-500 hover:text-surface-300 cursor-pointer uppercase tracking-widest transition-colors">
            Salir
          </button>
        </div>
      </div>
    </header>

    <!-- ── Main ────────────────────────────────────────────── -->
    <main class="max-w-6xl mx-auto px-6 py-10">

      <!-- ── Hero de progreso ─────────────────────────────── -->
      <div class="bg-surface-900 border border-surface-700 rounded-xl overflow-hidden card-elevated mb-10">
        <div class="p-7 flex flex-col sm:flex-row sm:items-start gap-6 sm:gap-10">

          <!-- Porcentaje grande -->
          <div class="shrink-0">
            <div class="font-serif text-6xl font-semibold text-surface-100 leading-none tabular-nums">
              {percentage}<span class="text-3xl text-surface-400 ml-1">%</span>
            </div>
            <p class="text-sm text-surface-500 mt-2">
              {totalCompleted} de {totalRequired} evaluaciones
            </p>
          </div>

          <!-- Separador vertical -->
          <div class="hidden sm:block w-px self-stretch bg-surface-700"></div>

          <!-- Stats por imagen -->
          <div class="flex flex-col justify-center gap-2.5 flex-1">
            <div class="flex items-center gap-2.5">
              <span class="w-2 h-2 rounded-full bg-green-500 shrink-0"></span>
              <span class="text-sm text-surface-300">
                <span class="font-medium tabular-nums text-surface-100">{countDone}</span>
                {countDone === 1 ? 'partitura completa' : 'partituras completas'}
              </span>
            </div>
            <div class="flex items-center gap-2.5">
              <span class="w-2 h-2 rounded-full bg-amber-400 shrink-0"></span>
              <span class="text-sm text-surface-300">
                <span class="font-medium tabular-nums text-surface-100">{countPartial}</span>
                en progreso
              </span>
            </div>
            <div class="flex items-center gap-2.5">
              <span class="w-2 h-2 rounded-full bg-surface-600 shrink-0"></span>
              <span class="text-sm text-surface-300">
                <span class="font-medium tabular-nums text-surface-100">{countNone}</span>
                sin empezar
              </span>
            </div>
          </div>

          <!-- CTA -->
          <div class="flex items-center sm:ml-auto">
            {#if firstIncomplete}
              <a
                href="/evaluate/{encodeURIComponent(firstIncomplete)}"
                class="inline-flex items-center gap-2 px-5 py-2.5 bg-accent-600 hover:bg-accent-700 text-white text-sm font-semibold rounded-lg cursor-pointer transition-colors"
              >
                Continuar
                <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                </svg>
              </a>
            {:else}
              <div class="inline-flex items-center gap-2 px-5 py-2.5 bg-green-500/10 border border-green-500/25 text-green-600 text-sm font-semibold rounded-lg">
                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                </svg>
                Completado
              </div>
            {/if}
          </div>
        </div>

        <!-- Barra de progreso full-width en el pie de la card -->
        <div class="h-1 bg-surface-800">
          <div
            class="h-1 transition-all duration-500 {percentage === 100 ? 'bg-green-500' : 'bg-accent-600'}"
            style="width: {percentage}%"
          ></div>
        </div>
      </div>

      <!-- ── Cabecera de la cuadrícula ────────────────────── -->
      <div class="flex items-center gap-3 mb-5">
        <h2 class="font-serif text-lg font-semibold text-surface-200 shrink-0">Partituras</h2>
        <span class="text-surface-600 text-sm tabular-nums shrink-0">({images.length})</span>
        <div class="flex-1 h-px bg-surface-700"></div>
      </div>

      <!-- ── Grid de imágenes ─────────────────────────────── -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {#each images as imageFilename}
          {@const progress = getImageProgress(imageFilename)}
          {@const status = getImageStatus(imageFilename)}
          <a
            href="/evaluate/{encodeURIComponent(imageFilename)}"
            class="group relative bg-surface-900 rounded-lg border overflow-hidden transition-all duration-200 card-elevated
              {status === 'done'
                ? 'border-green-500/30 hover:border-green-500/60'
                : status === 'partial'
                  ? 'border-amber-400/30 hover:border-amber-400/60'
                  : 'border-surface-700 hover:border-accent-600/40'}"
          >
            <!-- Thumbnail -->
            <div class="aspect-[4/3] bg-surface-850 overflow-hidden flex items-center justify-center p-3">
              <img
                src="/api/images/{imageFilename}"
                alt={imageFilename}
                class="max-w-full max-h-full object-contain transition-opacity duration-200
                  {status === 'done' ? 'opacity-70 group-hover:opacity-90' : 'opacity-85 group-hover:opacity-100'}"
                loading="lazy"
              />
            </div>

            <!-- Info footer -->
            <div class="px-3.5 py-3 border-t
              {status === 'done'
                ? 'border-green-500/20 bg-green-500/[0.03]'
                : status === 'partial'
                  ? 'border-amber-400/20 bg-amber-400/[0.03]'
                  : 'border-surface-700'}">
              <div class="flex items-center justify-between gap-2 mb-2">
                <span class="text-xs font-mono text-surface-500 truncate leading-tight">
                  {imageFilename}
                </span>
                {#if status === 'done'}
                  <div class="shrink-0 flex items-center gap-1">
                    <svg class="w-3 h-3 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                      <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                    </svg>
                    <span class="text-xs font-medium text-green-500">Completa</span>
                  </div>
                {:else if status === 'partial'}
                  <span class="shrink-0 text-xs font-medium text-amber-500">
                    {progress.completed}/{progress.total}
                  </span>
                {:else}
                  <span class="shrink-0 text-xs text-surface-600">—</span>
                {/if}
              </div>

              <!-- Progress track -->
              <div class="w-full h-1 bg-surface-800 rounded-full overflow-hidden">
                <div
                  class="h-1 rounded-full transition-all duration-300
                    {status === 'done' ? 'bg-green-500' : 'bg-accent-600'}"
                  style="width: {progress.total > 0 ? Math.round((progress.completed / progress.total) * 100) : 0}%"
                ></div>
              </div>
            </div>
          </a>
        {/each}
      </div>

    </main>
  </div>
{/if}
