// src/components/GridView.svelte
<script lang="ts">
  import ModelResponseCard from './ModelResponseCard.svelte';
  import type { ModelResponse, Evaluation, QuestionType } from '../lib/types';

  interface Props {
    responses: ModelResponse[];
    questionType: QuestionType;
    evaluations: Map<string, Evaluation>;
    onscore: (modelName: string, score: number) => void;
    oncomment: (modelName: string, comment: string) => void;
  }

  let { responses, questionType, evaluations, onscore, oncomment }: Props = $props();
</script>

<div class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
  {#each responses as response (response.modelo)}
    <ModelResponseCard
      {response}
      {questionType}
      evaluation={evaluations.get(response.modelo) || null}
      onscore={(score) => onscore(response.modelo, score)}
      oncomment={(comment) => oncomment(response.modelo, comment)}
    />
  {/each}
</div>

// src/components/react/GridView.tsx
import { motion } from "framer-motion";
import { ModelResponseCard } from "./ModelResponseCard";
import type { ModelResponse, Evaluation, QuestionType } from "../../lib/types";

interface GridViewProps {
  responses: ModelResponse[];
  questionType: QuestionType;
  evaluations: Map<string, Evaluation>;
  onScore: (modelName: string, score: number) => void;
  onComment: (modelName: string, comment: string) => void;
}

const container = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.07,
    },
  },
};

export function GridView({
  responses,
  questionType,
  evaluations,
  onScore,
  onComment,
}: GridViewProps) {
  return (
    <motion.div
      className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4"
      variants={container}
      initial="hidden"
      animate="visible"
    >
      {responses.map((response) => (
        <ModelResponseCard
          key={response.modelo}
          response={response}
          questionType={questionType}
          evaluation={evaluations.get(response.modelo) || null}
          onScore={(score) => onScore(response.modelo, score)}
          onComment={(comment) => onComment(response.modelo, comment)}
        />
      ))}
    </motion.div>
  );
}
